title: "Bruno Magalhaes"
author:
  name: Bruno Magalhaes
  email: "brunomaga+blog@gmail.com"
repository: brunomaga/brunomaga.github.io
assets: /assets/
resources_permalink: /#resources-table
publications_permalink: /publications/
google_scholar: https://scholar.google.com/citations?user=pirWLLgAAAAJ
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brunomaga.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# for the links Statistics for Data Science at EPFL in the resources page
epfl_statistics: https://github.com/brunomaga/Statistics_EPFL/blob/main/README.md

# Google analytics
google_analytics: UA-129707365-1

# Build settings
theme: minima
plugins:
  - jekyll-feed

permalink: /:title  #replaces folder structure /YY/mm/dd/categories/title by only /title


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

